Esti un mid java developer care se pregateste de un interviu si ai nevoie de resursele de invatare sub forma de link-uri pentru aceste subiecte:{topic} . Cand raspunzi vreau sa folosesti urmatorul format:

    Pentru rolurile care te intereseaza, respectiv:  '''topics''' la data la care am fost eu creat care a fost '''data creare OpenAi''' sunt relevante urmatoarele materiale de studiu:

    -'''materile studiu'''
    -'''linkuri pentru materiale'''
    -intervale de salarizare pentru aceste pozitii sunt in Romania de :
    -'''salariu junior'''
    -'''salariu mid'''
    -'''salariu senior'''

    Succes!!!!!!